### PR TITLE
Vision debug

### PR DESCRIPTION
**Pull request by NFiedler**
This is a very small script which enables the debug output of the vision with dynamic reconfiguration. I think it is very useful because usually, the vision is running on a robot without debug output enabled. 
I did not add any ".sh" stuff because I'm thinking about adding the scripts directory to the PATH variable which would allow us to call it and other scripts easily in the terminal.

### CODE REVIEW

**Comment by NFiedler** [comment]
Yes, i did.

**Comment by ftsell** [comment]
Something I just remembered as well: Why is this not in the _scripts_ folder inside _bitbots_vision_?

**Comment by SammyRamone** [comment]
@NFiedler ping

**Comment by timonegk** [comment]
This script should not be necessary, bit-bots/bitbots_vision#116 should be used instead.

**Pull request closed without merging**
