### PR TITLE
Switch back to upstream tf2_geometry_msgs

### PR DESCRIPTION
**Pull request by Flova**
## Proposed changes
- Remove PyKDL build from source
- Remove tf2_geometry_msgs

### CODE REVIEW

**Comment by jaagut** [comment]
We are removing this because we switched to releases or what is the reason behind this?

**Comment by Flova** [comment]
The tf2 upstream package should be available again, so we can use that. I still need to look if it is only released for jammy.

**Comment by Flova** [comment]
My docker is jammy, so I am not sure if the robot receives the update.

**Comment by jaagut** [comment]
Seems like `tf2_geometry_msgs` is not available in 20.04
@val-ba thanks for investigating!

**Review by jaagut — APPROVED** [review]

**Pull request merged**
